# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/SOC_Project/SOC_AES_PROJECT/SOC_project_our_IP/SOC_AES_Our_IP/SOC_AES_Our_IP.srcs/sources_1/bd/SOC_Our_IP/ip/SOC_Our_IP_processing_system7_0_0/SOC_Our_IP_processing_system7_0_0.xci
# IP: The module: 'SOC_Our_IP_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/SOC_Project/SOC_AES_PROJECT/SOC_project_our_IP/SOC_AES_Our_IP/SOC_AES_Our_IP.srcs/sources_1/bd/SOC_Our_IP/ip/SOC_Our_IP_processing_system7_0_0/SOC_Our_IP_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_Our_IP_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: h:/SOC_Project/SOC_AES_PROJECT/SOC_project_our_IP/SOC_AES_Our_IP/SOC_AES_Our_IP.srcs/sources_1/bd/SOC_Our_IP/ip/SOC_Our_IP_processing_system7_0_0/SOC_Our_IP_processing_system7_0_0.xci
# IP: The module: 'SOC_Our_IP_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/SOC_Project/SOC_AES_PROJECT/SOC_project_our_IP/SOC_AES_Our_IP/SOC_AES_Our_IP.srcs/sources_1/bd/SOC_Our_IP/ip/SOC_Our_IP_processing_system7_0_0/SOC_Our_IP_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SOC_Our_IP_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
