# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AES_Improved/AES_Improved.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_Improved || ORIG_REF_NAME==AES_Improved} -quiet] -quiet

# IP: bd/AES_Improved/ip/AES_Improved_processing_system7_0_0/AES_Improved_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_Improved_processing_system7_0_0 || ORIG_REF_NAME==AES_Improved_processing_system7_0_0} -quiet] -quiet

# IP: bd/AES_Improved/ip/AES_Improved_AES_improved_0_0/AES_Improved_AES_improved_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_Improved_AES_improved_0_0 || ORIG_REF_NAME==AES_Improved_AES_improved_0_0} -quiet] -quiet

# IP: bd/AES_Improved/ip/AES_Improved_auto_pc_0/AES_Improved_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_Improved_auto_pc_0 || ORIG_REF_NAME==AES_Improved_auto_pc_0} -quiet] -quiet

# IP: bd/AES_Improved/ip/AES_Improved_ps7_0_axi_periph_0/AES_Improved_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_Improved_ps7_0_axi_periph_0 || ORIG_REF_NAME==AES_Improved_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AES_Improved/ip/AES_Improved_rst_ps7_0_50M_0/AES_Improved_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_Improved_rst_ps7_0_50M_0 || ORIG_REF_NAME==AES_Improved_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/AES_Improved/AES_Improved_ooc.xdc
