# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/project/SoC_project/SoC_project.srcs/sources_1/bd/design_aes/ip/design_aes_processing_system7_0_0/design_aes_processing_system7_0_0.xci
# IP: The module: 'design_aes_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/project/SoC_project/SoC_project.srcs/sources_1/bd/design_aes/ip/design_aes_processing_system7_0_0/design_aes_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_aes_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: h:/project/SoC_project/SoC_project.srcs/sources_1/bd/design_aes/ip/design_aes_processing_system7_0_0/design_aes_processing_system7_0_0.xci
# IP: The module: 'design_aes_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/project/SoC_project/SoC_project.srcs/sources_1/bd/design_aes/ip/design_aes_processing_system7_0_0/design_aes_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_aes_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
