# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/esisar/SOC/soc_git/SOC_AES_PROJECT/SOC_project_our_IP_improved/project/SOC_AES_Improved.srcs/sources_1/bd/AES_Improved/ip/AES_Improved_rst_ps7_0_50M_0/AES_Improved_rst_ps7_0_50M_0.xci
# IP: The module: 'AES_Improved_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/esisar/SOC/soc_git/SOC_AES_PROJECT/SOC_project_our_IP_improved/project/SOC_AES_Improved.srcs/sources_1/bd/AES_Improved/ip/AES_Improved_rst_ps7_0_50M_0/AES_Improved_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_Improved_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/esisar/SOC/soc_git/SOC_AES_PROJECT/SOC_project_our_IP_improved/project/SOC_AES_Improved.srcs/sources_1/bd/AES_Improved/ip/AES_Improved_rst_ps7_0_50M_0/AES_Improved_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_Improved_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/esisar/SOC/soc_git/SOC_AES_PROJECT/SOC_project_our_IP_improved/project/SOC_AES_Improved.srcs/sources_1/bd/AES_Improved/ip/AES_Improved_rst_ps7_0_50M_0/AES_Improved_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_Improved_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/esisar/SOC/soc_git/SOC_AES_PROJECT/SOC_project_our_IP_improved/project/SOC_AES_Improved.srcs/sources_1/bd/AES_Improved/ip/AES_Improved_rst_ps7_0_50M_0/AES_Improved_rst_ps7_0_50M_0.xci
# IP: The module: 'AES_Improved_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/esisar/SOC/soc_git/SOC_AES_PROJECT/SOC_project_our_IP_improved/project/SOC_AES_Improved.srcs/sources_1/bd/AES_Improved/ip/AES_Improved_rst_ps7_0_50M_0/AES_Improved_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_Improved_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/esisar/SOC/soc_git/SOC_AES_PROJECT/SOC_project_our_IP_improved/project/SOC_AES_Improved.srcs/sources_1/bd/AES_Improved/ip/AES_Improved_rst_ps7_0_50M_0/AES_Improved_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_Improved_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/esisar/SOC/soc_git/SOC_AES_PROJECT/SOC_project_our_IP_improved/project/SOC_AES_Improved.srcs/sources_1/bd/AES_Improved/ip/AES_Improved_rst_ps7_0_50M_0/AES_Improved_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_Improved_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
