# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/SOC_Project/SOC_AES_PROJET/SOC_AES_PROJECT/VHDL_INTR/VHDL_INTR/VHDL_INTR.srcs/sources_1/bd/AES_F/ip/AES_F_auto_pc_0/AES_F_auto_pc_0.xci
# IP: The module: 'AES_F_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/SOC_Project/SOC_AES_PROJET/SOC_AES_PROJECT/VHDL_INTR/VHDL_INTR/VHDL_INTR.srcs/sources_1/bd/AES_F/ip/AES_F_auto_pc_0/AES_F_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_F_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: h:/SOC_Project/SOC_AES_PROJET/SOC_AES_PROJECT/VHDL_INTR/VHDL_INTR/VHDL_INTR.srcs/sources_1/bd/AES_F/ip/AES_F_auto_pc_0/AES_F_auto_pc_0.xci
# IP: The module: 'AES_F_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/SOC_Project/SOC_AES_PROJET/SOC_AES_PROJECT/VHDL_INTR/VHDL_INTR/VHDL_INTR.srcs/sources_1/bd/AES_F/ip/AES_F_auto_pc_0/AES_F_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_F_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
