# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SOC_Our_IP/SOC_Our_IP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_Our_IP || ORIG_REF_NAME==SOC_Our_IP} -quiet] -quiet

# IP: bd/SOC_Our_IP/ip/SOC_Our_IP_processing_system7_0_0/SOC_Our_IP_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_Our_IP_processing_system7_0_0 || ORIG_REF_NAME==SOC_Our_IP_processing_system7_0_0} -quiet] -quiet

# IP: bd/SOC_Our_IP/ip/SOC_Our_IP_AES_Our_IP_0_0/SOC_Our_IP_AES_Our_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_Our_IP_AES_Our_IP_0_0 || ORIG_REF_NAME==SOC_Our_IP_AES_Our_IP_0_0} -quiet] -quiet

# IP: bd/SOC_Our_IP/ip/SOC_Our_IP_auto_pc_0/SOC_Our_IP_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_Our_IP_auto_pc_0 || ORIG_REF_NAME==SOC_Our_IP_auto_pc_0} -quiet] -quiet

# IP: bd/SOC_Our_IP/ip/SOC_Our_IP_ps7_0_axi_periph_0/SOC_Our_IP_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_Our_IP_ps7_0_axi_periph_0 || ORIG_REF_NAME==SOC_Our_IP_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/SOC_Our_IP/ip/SOC_Our_IP_rst_ps7_0_50M_0/SOC_Our_IP_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SOC_Our_IP_rst_ps7_0_50M_0 || ORIG_REF_NAME==SOC_Our_IP_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/SOC_Our_IP/SOC_Our_IP_ooc.xdc
