# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_design/system_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design || ORIG_REF_NAME==system_design} -quiet] -quiet

# IP: bd/system_design/ip/system_design_processing_system7_0_0/system_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_processing_system7_0_0 || ORIG_REF_NAME==system_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_AES_Custom_VHDL_0_0/system_design_AES_Custom_VHDL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_AES_Custom_VHDL_0_0 || ORIG_REF_NAME==system_design_AES_Custom_VHDL_0_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_ps7_0_axi_periph_0/system_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_rst_ps7_0_50M_0/system_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/system_design/ip/system_design_auto_pc_0/system_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_auto_pc_0 || ORIG_REF_NAME==system_design_auto_pc_0} -quiet] -quiet

# XDC: bd/system_design/system_design_ooc.xdc
