# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AES_F/AES_F.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_F || ORIG_REF_NAME==AES_F} -quiet] -quiet

# IP: bd/AES_F/ip/AES_F_processing_system7_0_0/AES_F_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_F_processing_system7_0_0 || ORIG_REF_NAME==AES_F_processing_system7_0_0} -quiet] -quiet

# IP: bd/AES_F/ip/AES_F_AES_ENC_0_0/AES_F_AES_ENC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_F_AES_ENC_0_0 || ORIG_REF_NAME==AES_F_AES_ENC_0_0} -quiet] -quiet

# IP: bd/AES_F/ip/AES_F_AES_DEC_0_1/AES_F_AES_DEC_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_F_AES_DEC_0_1 || ORIG_REF_NAME==AES_F_AES_DEC_0_1} -quiet] -quiet

# IP: bd/AES_F/ip/AES_F_xlconcat_0_0/AES_F_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_F_xlconcat_0_0 || ORIG_REF_NAME==AES_F_xlconcat_0_0} -quiet] -quiet

# IP: bd/AES_F/ip/AES_F_xbar_0/AES_F_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_F_xbar_0 || ORIG_REF_NAME==AES_F_xbar_0} -quiet] -quiet

# IP: bd/AES_F/ip/AES_F_auto_pc_0/AES_F_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_F_auto_pc_0 || ORIG_REF_NAME==AES_F_auto_pc_0} -quiet] -quiet

# IP: bd/AES_F/ip/AES_F_ps7_0_axi_periph_0/AES_F_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_F_ps7_0_axi_periph_0 || ORIG_REF_NAME==AES_F_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AES_F/ip/AES_F_rst_ps7_0_50M_0/AES_F_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_F_rst_ps7_0_50M_0 || ORIG_REF_NAME==AES_F_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/AES_F/AES_F_ooc.xdc
