# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_aes/design_aes.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aes || ORIG_REF_NAME==design_aes} -quiet] -quiet

# IP: bd/design_aes/ip/design_aes_processing_system7_0_0/design_aes_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aes_processing_system7_0_0 || ORIG_REF_NAME==design_aes_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_aes/ip/design_aes_AES_IP_0_0/design_aes_AES_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aes_AES_IP_0_0 || ORIG_REF_NAME==design_aes_AES_IP_0_0} -quiet] -quiet

# IP: bd/design_aes/ip/design_aes_ps7_0_axi_periph_0/design_aes_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aes_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_aes_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_aes/ip/design_aes_rst_ps7_0_50M_0/design_aes_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aes_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_aes_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_aes/ip/design_aes_auto_pc_0/design_aes_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aes_auto_pc_0 || ORIG_REF_NAME==design_aes_auto_pc_0} -quiet] -quiet

# XDC: bd/design_aes/design_aes_ooc.xdc
