# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AES_ECB/AES_ECB.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_ECB || ORIG_REF_NAME==AES_ECB} -quiet] -quiet

# IP: bd/AES_ECB/ip/AES_ECB_processing_system7_0_0/AES_ECB_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_ECB_processing_system7_0_0 || ORIG_REF_NAME==AES_ECB_processing_system7_0_0} -quiet] -quiet

# IP: bd/AES_ECB/ip/AES_ECB_AES_ECB_2_version2_0_0/AES_ECB_AES_ECB_2_version2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_ECB_AES_ECB_2_version2_0_0 || ORIG_REF_NAME==AES_ECB_AES_ECB_2_version2_0_0} -quiet] -quiet

# IP: bd/AES_ECB/ip/AES_ECB_auto_pc_0/AES_ECB_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_ECB_auto_pc_0 || ORIG_REF_NAME==AES_ECB_auto_pc_0} -quiet] -quiet

# IP: bd/AES_ECB/ip/AES_ECB_ps7_0_axi_periph_0/AES_ECB_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_ECB_ps7_0_axi_periph_0 || ORIG_REF_NAME==AES_ECB_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AES_ECB/ip/AES_ECB_rst_ps7_0_50M_0/AES_ECB_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AES_ECB_rst_ps7_0_50M_0 || ORIG_REF_NAME==AES_ECB_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/AES_ECB/AES_ECB_ooc.xdc
